# -*- coding: utf-8 -*-
"""callbacks_helper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJEEbVVixhxjKPOQMfyZwEZ_QRbK5t0h
"""



import tensorflow as tf
tf.__version__

# Creating Tensorboard callback
import datetime
def create_tensorboard_callback(dir_name, experiment_name):
  '''
  Log the performance of multiple models and veiw and compare
  those models in visual way on Tensorboard.

  Args:
  dir_name: Overall log directory.
  experiment_name: Name of particular Experiment. (Model)

  '''
  log_dir = dir_name + '/' + experiment_name + '/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
  tensorboard_callback= tf.keras.callbacks.TensorBoard(
      log_dir=log_dir
  )
  print(f'Saving TensorBoard log files to: {log_dir} directory')
  return tensorboard_callback

# Creating ModelCheckpoint Callback
def create_modelcheckpoint_callback(checkpoint_path):
  '''
  Save your model as it training so you can stop training if
  needed and come back continue off where you left.

  Args:
  checkpoint_path: The file path of experiment saved weights.
  example->
  checkpoint_path = "ten_percent_model_checkpoints_weights/checkpoint.ckpt"
  '''
  checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                         save_weights_only=True,
                                                         save_best_only=True,
                                                         save_freq='epoch',
                                                         verbose=1)

